resources:
- ../../base

patches:
- path: patch-replicas.yaml
- path: patch-db-secret.yaml

images:
- name: booking-service:latest
  newName: 396183525704.dkr.ecr.us-east-1.amazonaws.com/booking-service
  newTag: 17de58d751fd76a7299dff3ea2b193853d46a076
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
