apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: booking-db-dev-conn
              key: address
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: booking-db-dev-conn
              key: port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: booking-db-dev-conn
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: booking-db-dev-conn
              key: password
        - name: DB_NAME
          value: "bookings"
        - name: DB_DSN
          value: "host=$(DB_HOST) user=$(DB_USER) password=$(DB_PASSWORD) dbname=$(DB_NAME) port=$(DB_PORT) sslmode=require"
